spring:
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    platform: mysql
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/microservicio_product_v2?serverTimezone=UTC
    username: root
    password: Kojinanjo1@
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    enabled: true


server:
  port: 8083

active-mq:
  broker-url: tcp://localhost:61616
  password-recovery-queue: user.password-recovery.queue

jwt:
  secret: Q2xhdmVDb21wbGVqYURlRGVzY2lmcmFyUXVlTmFkaWVMYVNhYmUxMjM0NTY3ODk=
  expiration: 3600000  # 1 hora